name: Continuous Integration
on: [push]
jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run lint
      - run: npm run test:ci
      - uses: actions/upload-artifact@v1
        with:
          name: coverage
          path: coverage
      - run: bash <(curl -s https://codecov.io/bash)
